title: "Simulated Reality"
subtitle: "An Exciting Journey into the World of Quantum Mechanics, Brain-Machine Interfaces, and Transhumanism"
toc-title: "Table of Contents"
author: "László Fazekas"
language: en
latex-language: english
rights: "© 2026 László Fazekas"
copyright-page: |
  Copyright © 2026 by László Fazekas

  All rights reserved. No part of this publication may be reproduced, stored,
  or transmitted in any form or by any means, electronic, mechanical,
  photocopying, recording, scanning, or otherwise without written permission
  from the publisher. It is illegal to copy this book, post it to a website,
  or distribute it by any other means without permission.

  To contact the author, please visit his personal website at  
  thebojda.github.io

  First edition

  This book was professionally typeset in LaTeX.  
  Find out more at latex-project.org
dedication: |
  I am grateful to my wife, Júlia, for the beautiful cover, and to my son, Dorián, 
  for letting me use our favorite shared photograph on the cover of my first book.
dedication-ebook: |
  Dear Reader,

  Simulated Reality is my first book. I’ve put a great deal of work into it, but I decided to experiment with a different kind of business model. The eBook is available completely free of charge—so anyone can read it and decide afterward how much they liked it.

  My primary goal with this book isn’t to make money, but to reach as many people as possible. You can really help with that: if you enjoyed the book, please consider leaving a positive review, sharing it on social media, or simply telling your friends about it. These small actions make a huge difference in helping the book spread organically.

  And if you liked it enough that you would have paid for it, you can support me by purchasing a copy for yourself—or as a gift for a friend—on Amazon, in paperback or hardcover format.

  You can find the book here:
  https://www.amazon.com/dp/B0GGJ3HSZJ

  Thank you!